Repository TomerFi/auto-me-bot, pull requests merged in 2022-08, with the labels that each got.

#51 feat: add option to configure commit- rules
  .github/auto-me-bot.yml
  docs/configuration.md
  src/handlers/pr-conventional-commits.js
  tests/handlers/pr-conventional-commits.test.js
Labels: status: approved, size: m

#56 feat: passing only relevant configurations to handler
  src/auto-me-bot.js
  src/handlers/pr-conventional-commits.js
  tests/handlers/pr-conventional-commits.test.js
Labels: status: approved, size: s

#57 fix failing tests
  tests/auto-me-bot.test.js
Labels: status: needs review, size: s

#59 Ignore bots signoff check
  src/handlers/pr-signed-commits.js
  tests/handlers/pr-signed-commits.test.js
Labels: status: needs review, size: m

#64 chore: logging context and config for troubleshooting
  package-lock.json
  package.json
  src/auto-me-bot.js
Labels: size: xs, status: needs review
